import pandas as pd
import sys
from datetime import datetime



def converte_df_to_dict(df_to_dict,df_to_map):
    """
    Receives a df containing the GSM and other metadata
    columns extracted from xml_parser script, and Histones
    df generated by compare_dbs script. Returns a df containing
    the mapped Gsm info from xml_parser output. 
    """

    dict_map = df_to_dict.set_index('Gsm').T.to_dict()
    
    for k,v in dict_map.items():
        for index,row in df_to_map.iterrows():
            # print(k)
            # print(row['GSM'])
            if k == row['Gsm']:
                print(k, row['Gsm'])

                for col in v.keys():

                    df_to_map.at[index, col] = v[col]
            
                break
                    

    # print(df_to_map)
    return df_to_map


def main():

    print('Starting...')
    date = datetime.now().strftime("%Y_%m_%d")
    df_to_dict = pd.read_csv(sys.argv[1], sep="\t") #output xml fill parse
    df_to_map = pd.read_csv(sys.argv[2],sep="\t") #compiled dbs (tab separator for histone table)

    df_to_map_1 =  converte_df_to_dict(df_to_dict,df_to_map)
    df_to_map_1.to_csv('Histones_DBs'+date+'_gsm_xml_filled.tsv', index=False, sep="\t")
    
    print('Done')

if __name__ == "__main__":


    main()
